### ISSUE TITLE
Server Broken

### ISSUE THREAD

**Issue by varHarrie** [tarinoita/Spice-of-Life-Sweet-Potato#10]
**Description**
When disconnect from server, then show an error on server side: 
Exception caught during firing event: Player must have effect benefits capability attached, but none was found.

**Crashlog**

```
[Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Player must have effect benefits capability attached, but none was found.
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class com.kreezcraft.mobsunscreen.DamnSun entityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		2: ASM: class com.tarinoita.solsweetpotato.tracking.benefits.BenefitsHandler tickBenefits(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
com.tarinoita.solsweetpotato.tracking.benefits.EffectBenefitsCapability$EffectsBenefitsNotFoundException: Player must have effect benefits capability attached, but none was found.
	at TRANSFORMER/forge@40.1.73/net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:281)
	at TRANSFORMER/solsweetpotato@1.18.2-1.0.3/com.tarinoita.solsweetpotato.tracking.benefits.EffectBenefitsCapability.get(EffectBenefitsCapability.java:27)
	at TRANSFORMER/solsweetpotato@1.18.2-1.0.3/com.tarinoita.solsweetpotato.tracking.benefits.BenefitsHandler.tickBenefits(BenefitsHandler.java:36)
	at net.minecraftforge.eventbus.ASMEventHandler_29_BenefitsHandler_tickBenefits_LivingUpdateEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.1.73/net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:297)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2581)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.player.Player.m_8119_(Player.java:250)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:574)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.players.PlayerList.remove(PlayerList.java:380)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_7026_(ServerGamePacketListenerImpl.java:1404)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection.m_129541_(Connection.java:396)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:168)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1055)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:376)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:963)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:786)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:286)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
Connects to a server with this mod, and then disconnect.
Removes this mod from server and client, everthing is ok.

**Mod version and Forge version**
Mod: solsweetpotato-1.18.2-1.0.3.jar
Forge: 40.1.76

**Comment by tarinoita** [comment]
Hm, I haven't been experiencing this on my server, though it's on 1.19.2 and a more recent version of Forge. If updating Forge is an option, you might try that.

1. Everyone's definitely playing with sweet potato version 1.0.3, right? There was a serious problem with this kind of crash before 1.0.2, but I thought I had fixed it.
2. Does it happen for every player, every time they disconnect?
3. Does it crash the server, the client, or both?
4. Does it happen when ONLY this mod is installed? If not, can you narrow it down to see which other mod(s) may be interacting poorly?
